### ISSUE TITLE
Inline attachment support when creating message from MailMessage

### ISSUE THREAD

**Issue by marisks** [wildbit/postmark-dotnet#15]
Seems that it do not add CID to PostmarkMessageAttachment when constructed from MailMessage:

https://github.com/wildbit/postmark-dotnet/blob/master/src/Postmark/Model/PostmarkMessage.cs#L110

**Comment by atheken** [comment]
This commit resolves the issue:
https://github.com/wildbit/postmark-dotnet/commit/4cd2b7dca78be74709082421b588ae4732582b57

Thanks for reporting it!
