### ISSUE TITLE
InnerException when passing PostmarkBounceType to GetBouncesAsync

### ISSUE THREAD

**Issue by ryan-shelby** [wildbit/postmark-dotnet#22]
An error is thrown when passing any PostmarkBounceType to GetBounceAsync.
 Error only occurs when passing the type.  Works fine when passing all other parameters (count, offset, etc.) using version 2.0.76

Additional Info:
Inner Exception {"Bad boolean value 'HardBounce'"}

at PostmarkDotNet.PCL.PostmarkClientBase.<ProcessRequestAsync>d__2`2.MoveNext() in c:\projects\postmark-dotnet\src\Postmark.PCL\PostmarkClientBase.cs:line 121
--- End of stack trace from previous location where exception was thrown ---

**Comment by atheken** [comment]
@ryan-shelby Thanks for reporting! I've applied a fix and we should have a NuGet build shortly.

**Comment by ryan-shelby** [comment]
Wow thanks so much for the quick update!

**Comment by atheken** [comment]
@ryan-shelby you should be able to pull version 2.0.80 from NuGet and the issue should be resolved. Thanks again for reporting it.

**Comment by ryan-shelby** [comment]
Thanks so much!  Works great!
