### ISSUE TITLE
Please remove the powershell script that opens the release notes!!!!!

### ISSUE THREAD

**Issue by hisuwh** [wildbit/postmark-dotnet#25]
Whilst I realise the intention of this was to make us aware of the changes in the latest version.

What this serves to do is annoy the hell out of me as it opens every single time I open the package manager console - not good when I am already struggling with package restore/migrations/etc and so already annoyed when I open the console just to have your github page pop up in my developer window for the thousandth time.

**Comment by atheken** [comment]
@hisuwh I'm sorry this is happening.

We're using Init.ps1, which, according to the docs, should only run once when the package is installed in your solution "Init.ps1 runs the first time a package is installed in a solution." -- http://docs.nuget.org/create/Creating-and-Publishing-a-Package, do you know which version of the NuGet Package Manager, and Visual Studio you're running? It would be good to know if this is an issue specific to our package, or a more general bug with NuGet under specific circumstances.

**Comment by hisuwh** [comment]
This is Visual Studio 2013
Part of the problem as well is that when you are working on different branches (as any real world company does) you end up restoring your packages relatively regularly so it may only be running on install but that is still frequent enough to be annoying

**Comment by kfrancis** [comment]
It would be nice, if it's not removed, to at least pretty the page up so that it doesn't open with warnings.

**Comment by atheken** [comment]
See response from #32

**Comment by benjamingr** [comment]
We reinstall all packages on builds and this is super annoying. Just FYI.

**Comment by atheken** [comment]
@benjamingr The updated nuget packages with this disabled are live on nuget.org. Please re-open this issue if you continue seeing the release notes on install.

**Comment by benjamingr** [comment]
Awesome, thanks a lot!
