### ISSUE TITLE
The use of "X-PostmarkTag" to Tag a MailMessage is unexpected - "X-PM-Tag" would make more sense

### ISSUE THREAD

**Issue by frankvaneykelen** [wildbit/postmark-dotnet#27]
When trying to tag a System.Net.Mail.MailMessage I first tried this (after looking a the Raw Source of a message that I sent which was tagged using a PostmarkMessage.Tag):

    message.Headers.Add("X-PM-Tag", "TenantId-4fda408a-9481-4014-9f17-301eceb755d0"); 

That did not work. When checking the source code I found out that I had to use this:

    message.Headers.Add("X-PostmarkTag", "TenantId-4fda408a-9481-4014-9f17-301eceb755d0");

I did not expect this - I assumed the header keys would be the same.

These are the relevant lines from the source code (ConvertSystemMailMessage):

            var header = message.Headers.Get("X-PostmarkTag");
            if (header != null)
            {
                pm.Tag = header;
            }

**Comment by atheken** [comment]
@frankvaneykelen You're right, this is just a bug. I'll add handling for the correct header "X-PM-Tag" (and still keep this one around for backwards compatibility.)

**Comment by atheken** [comment]
Thanks for the report, @frankvaneykelen - I'll push bug fix NuGet package once the tests pass for this in CI.

**Comment by frankvaneykelen** [comment]
Thanks!
