### ISSUE TITLE
Potential problem with bounceId defined as int?

### ISSUE THREAD

**Issue by frankvaneykelen** [wildbit/postmark-dotnet#29]
Methods like `ActivateBounceAsync` and `GetBounceAsync` take an integer `bounceId` as parameter. I noticed that the ID of a bounce I retrieved from the API today was 849991712. The max value of an int is 2147483647. If the primary key of the bounces is incremental that means that it's at 40% of the maximum that can be stored as an int. When it passes 2147483647 methods like the above will break.

Please tell me that I'm wrong!

FYI - the int in `ActivateBounceAsync(int bounceId)` inherits from Int32:

    public struct Int32 : IComparable, IFormattable, IConvertible, IComparable<int>, IEquatable<int>
    {
        // Summary:
        //     Represents the largest possible value of an System.Int32. This field is constant.
        public const int MaxValue = 2147483647;
        //
        // Summary:
        //     Represents the smallest possible value of System.Int32. This field is constant.
        public const int MinValue = -2147483648;

**Comment by jptoto** [comment]
@frankvaneykelen It's true that the int(32) value will max out eventually. The integer ID is there as a legacy ID at this point and I think we'll eventually move away from it. As it is, Postmark is five and a half years old and we've only used 40% of the ints available so I think we've got time to migrate to whatever the next ID type will be. At that time, we'll update the Postmark lib and note the change.

Thanks for the note!
