### ISSUE TITLE
PostmarkDotNet.Model.To.Name is an object instead of a string

### ISSUE THREAD

**Issue by frankvaneykelen** [wildbit/postmark-dotnet#30]
```
public class To
{
    public To();

    public string Email { get; set; }
    public object Name { get; set; } // <== this
}
```

I would have expected it to be a string. Now I have to do stuff like `outboundMessageDetail.To.First().Name.ToString()`

The same goes for Bcc.Name and Cc.Name.

If there's no reason to define the Name as an object I suggest changing it to string.

PS: Sorry for hammering the Issues board ;-)

**Comment by atheken** [comment]
@frankvaneykelen Thanks for the note. I'll review it and make a change if appropriate. Some of this might have to do with how System.Mail is laid out, but I haven't checked that API yet.

(No need to apologize for "hammering" the issues board, as that's what it's here for. We appreciate you taking the time to report things!)

**Comment by atheken** [comment]
Thanks, this will be resolved in the next release.
