### ISSUE TITLE
Add documentation for TemplatedPostmarkMessage please!

### ISSUE THREAD

**Issue by sergeydgr8** [wildbit/postmark-dotnet#34]
There is absolutely no documentation or examples on how to send templated emails in .NET. Would it be possible to have it written up, as it's really ambiguous on how to use the TemplateModel object to send data to Postmark.

**Comment by atheken** [comment]
Hi Sergey, I will get some docs in there, but basically, you can send any object that can be serialized to JSON by JSON.Net, *except* Scalars and Collections (the `TemplateModel` _may include_ values that are scalar or collections, but the top-level object must be an object as defined by JSON/Javascript). For more general information about the Postmark Template system, please have a look at this article: http://blog.postmarkapp.com/post/125849089273/special-delivery-postmark-templates Feel free to open a support case with questions. We can get back to you usually very quickly.

**Comment by sergeydgr8** [comment]
Hi Andrew, thanks for the response! I figured out to use a Dictionary for the template model, but perhaps using JSON would be more efficient. Will keep an eye out for documentation.

**Comment by atheken** [comment]
I've added docs inline on the client, and also written up how to send using a template in the wiki (https://github.com/wildbit/postmark-dotnet/wiki/Sending-Using-a-Template), please feel free to re-open the issue if you have questions/comments!
