### ISSUE TITLE
Missing properties in PostmarkInboundMessage

### ISSUE THREAD

**Issue by NoelOConnell** [wildbit/postmark-dotnet#37]
Hi,

PostmarkInboundMessage seems to be missing Bcc and BccFull.

Also BccFull, ToFull and CcFull are missing the MailboxHash property.

Can I submit a PR to add these in or are they missing for some reason?

Thanks

**Comment by atheken** [comment]
Hi @NoelOConnell,

There's no specific reason these are not available, just haven't had a chance to add them. We'd be happy to accept a PR if you have time to update the models. :-)

**Comment by NoelOConnell** [comment]
Sure, I'll try to submit a PR in the next few days with the updated models.

**Comment by atheken** [comment]
@BenJenkinson - Thanks for taking care of this. It is really appreciated!
