### ISSUE TITLE
BounceMessage and OpenMessage objects

### ISSUE THREAD

**Issue by NeilBostrom** [wildbit/postmark-dotnet#40]
When receiving posts from Webhooks, you have a class for PostmarkInboundMessage that can be used in ASP.NET MVC Web Api. I wasn't able to find matching classes for Bounce and Open?

I found PostmarkOpen and PostmarkBounce which are close but are missing some properties:

Open webhook also returns:

            public DateTime ReceivedAt { get; set; }
            public string Tag { get; set; }
            public string Recipient { get; set; }

Bounce webhook also returns:

            public int TypeCode { get; set; }
            public string Name { get; set; }

If these classes don't exist, did you want me to PR the classes I made?

**Comment by atheken** [comment]
Hi @NeilBostrom, thanks for volunteering! We'd be happy to get a PR on this if you have time to work on it.
