### ISSUE TITLE
Dotnet Core Support

### ISSUE THREAD

**Issue by sbosell** [wildbit/postmark-dotnet#47]
This library doesn't seem to work with aspnet core.  Can you publish your plans for updating this library?

**Comment by jcemoller** [comment]
I really had to use this library for an ASP.NET Core application, so I upgraded the existing PCL library to NET Standard. Works perfect from ASP.NET Core. Please note however that there is a bug in ASP.NET Core 1.1 that will not allow you to build the library and reference it in your project as an assembly from file. You need to either pack it as a NuGet package (that is what I had to do) or include this library as a project in your solution.

Forked at [https://github.com/jcemoller/postmark-dotnet](https://github.com/jcemoller/postmark-dotnet).

Happy e-mailing!

**Comment by atheken** [comment]
@jcemoller Thanks, we do plan to support dotnet core (we're using it internally for a couple of our services now).

I'll have a look at the fork and see if we can integrate it.

**Comment by jculverwell** [comment]
Probably worth checking if it works out of the box with .Net Standard 2.0

**Comment by jordanbrowneb** [comment]
@atheken Any update on publishing this library for dotnet core?

**Comment by mattwoberts** [comment]
Ping. I am/was considering moving to postmark app, but the absence of a .net core library will pretty much stop me from going down this road :(

**Comment by jcemoller** [comment]
@mattwoberts @jordanbrowneb Feel free to use my _unofficial_ library port until we get an official Postmark dotnet core library. I have put it on [NuGet](https://www.nuget.org/packages/Postmark-netstd/2.0.103-dev) (**Postmark-netstd**) for easy install. Works like a charm in all of my core projects.

**Comment by atheken** [comment]
I am planning to dedicate some time to updating the library and releasing for .net core in the next month -- early August timeframe.

**Comment by jculverwell** [comment]
Thank you, probably worth waiting until core 2.0 is out which is probably in the same timeframe

**Comment by atheken** [comment]
We will probably want to support the current version of .net core for
awhile. When I have a chance to review how we'll do it, we'll make that
decision. FWIW, I think PCLs (which we already publish) should actually
work in core 2.0, but I'm still a little bit fuzzy on the framework+runtime
venn diagram.

//Andrew

**Comment by jculverwell** [comment]
Now that .Net Core 2.0 is out can this now be bumped to be .Net Standard 2.0.  Thanks Jim

**Comment by atheken** [comment]
@jculverwell I've been working on moving the build and tooling to .net core and Travis CI. Right now, we're looking at releasing two assemblies in the main package, one compatible with .net 2.0+, and .net standard 1.2+ (we don't use any 4.6 syntax features, and .net standard is implemented with 4.5+, so we can cover more runtimes with it)

I'm not aware of any specific advantage of using .net standard 2.0, over 1.2 for the Postmark library, other than access to more "BCL" assemblies, but we don't need anything in there. (You can follow along, here, if you want: https://travis-ci.org/wildbit/postmark-dotnet)

**Comment by jculverwell** [comment]
Great news, as you say no advantage in using.net standard 2.0 more than happy with 1.2.

**Comment by atheken** [comment]
Hey all, if you're anxiously awaiting a .net core package, you should be able to try out an updated nuget package, it's on NuGet as a pre-release package: https://www.nuget.org/packages/Postmark/3.0.0-preview1

As indicated by the versioning, this will introduce some breaking changes over 2.x libs, primarily:

- Many method calls allowed you to pass just `text` for the message body, and we would attempt to determine if you meant `HTMLBody` or `TextBody` by "sniffing" the content. Methods now require you to pass one or both of these bodies as parameters.
- Removal of synchronous API calls (only Task-based calls are supported, so you'll need to wrap async calls into `Task.Run(...).Wait()` calls)
- Moving forward, we plan to support all frameworks that implement the .net standard 1.1 (so you'll need to reference the older packages for .net 2.0-4.0 support).
- Removal of convenience functions that map System.Net classes to the Postmark classes

If you do try it out and have a good (or bad) experience, let us know.

**Comment by atheken** [comment]
This is released, and should be in your nuget feeds in a few minutes!
