### ISSUE TITLE
Bounces do not contain all the available data

### ISSUE THREAD

**Issue by vaustt** [wildbit/postmark-dotnet#49]
Some assets are missing from returned bounces, notably the intended recipients email address.

It would probably also be useful to be able to access the raw return result of a request too, in addition to the results of the Newtonsoft deserialisation.

The issue is evidenced here:
![capture](https://cloud.githubusercontent.com/assets/27749210/25158844/4d063cce-24a3-11e7-8718-bfa9f4990044.PNG)

As you can see, a few attributes are missing - "From", "Name", "ServerID", etc

**Comment by atheken** [comment]
These have been added and are now available in version 2.2.1 on NuGet.
