### ISSUE TITLE
Document tread-safety guarantees for PostmarkClient

### ISSUE THREAD

**Issue by anton-gogolev** [wildbit/postmark-dotnet#50]
I could not find anything with regards to whether `PostmarkClient` instances are thread-safe or not. Looking through the source code I haven't seen anything immediately non-thread-safe, but I'd still like to get a confirmation straight from the horse's mouth.

**Comment by atheken** [comment]
I haven't specifically audited the code for thread-safety, but it _should_ be thread safe. `PostmarkClient` is fairly light-weight, so you should be fine to instantiate one for each request if you're concerned about this.

**Comment by anton-gogolev** [comment]
Whoopsies, forgot to respond. 

As far as I know, the official recommendation is to reuse a single HttpClient across requests (not sure about threads), so reinstantiating a PostmarkClient for each send is somewhat in violation with this guidance.
