### ISSUE TITLE
.NET standard 2

### ISSUE THREAD

**Issue by DavidDeSloovere** [wildbit/postmark-dotnet#52]
Any plan one releasing an update that also targets .net standard 2?

**Comment by atheken** [comment]
@DavidDeSloovere -- I'm not sure what you mean?

The current released version targets .net standard 1.1, which is a subset of .net standard 2.0, it should install and work without modification.

Are you seeing something different?

**Comment by DavidDeSloovere** [comment]
I'm kinda guessing that targeting .net standard 2.0 would result in not needing System.Net.Http, but I might be wrong. If you have a look at this package, it has not extra dependencies under .NETStandard2.0 https://www.nuget.org/packages/Newtonsoft.Json/11.0.1-beta3

**Comment by atheken** [comment]
I'm not sure that Json.net is a good comparison. It hasn't had a dependency on `System.Net.Http` for at least several releases, and maybe never(?).

The postmark client uses `System.Net.Http.HttpClient` to actually make REST requests to our API. .Net standard 2.0 defines that the `System.Net.Http` namespace is part of the standard, so the dependency wouldn't go away, it would just be implicitly provided by requiring the 2.0 standard library. This would also require users of the postmark library to take a (much larger) dependency on .net standard 2.0 when we add/update endpoints.

Are there other benefits to requiring .net standard 2.0+?

**Comment by DavidDeSloovere** [comment]
Ok. Think I'm getting it now. Thanks for your time.
