### ISSUE TITLE
PostmarkMessage constructor ignores value of headers argument

### ISSUE THREAD

**Issue by lucaspimentel** [wildbit/postmark-dotnet#55]
The following `PostmarkMessage` constructor overload ignores the `headers` argument and instead always create a new `HeaderCollection`:
```
PostmarkMessage(string from,
                string to,
                string subject,
                string textBody,
                string htmlBody,
                HeaderCollection headers = null)
```

Line 33 of `PostmarkMessage.cs` is currently
```
Headers = headers = new HeaderCollection();
```
but should probably be
```
Headers = headers ?? new HeaderCollection();
```

I created pull request #54 to fix this issue.

**Comment by atheken** [comment]
Thanks! This will go out in the next release.
