### ISSUE TITLE
Postmark-dotnet v3 creates multiple instances of HttpClient

### ISSUE THREAD

**Issue by MrKevHunter** [wildbit/postmark-dotnet#56]
If you create the simplest Console app to use with the client

```          
PostmarkClient client = new PostmarkClient("POSTMARK_API_TEST");
PostmarkMessage msg = new PostmarkMessage("Kev@Hunter.com","Tom@Robinson.com","Subject","Body","Body");
 var x = client.SendMessageAsync(msg).Result;
 x = client.SendMessageAsync(msg).Result;
```
Multiple instances of HttpClient will be created, but this is not correct, A single httpclient should be created and reused as referenced in this article

https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/

I would submit a PR but first you would need to decide what to do about the timeout property as this cannot be changed once  a `HttpClient` has been instantiated

**Comment by anton-gogolev** [comment]
That's what I was referring to in #50.

We've worked around this issue as follows:

    public class PostmarkHttpClient : ISimpleHttpClient
    {
        private readonly HttpClient httpClient;

        public TimeSpan Timeout
        {
            get => httpClient.Timeout;
            set
            {
                //
                // Attempts to set this value outside of constructor will fail with
                // System.InvalidOperationException: This instance has already started
                // one or more requests. Properties can only be modified before sending
                // the first request.
            }
        }

        public PostmarkHttpClient(TimeSpan timeout)
        {
            httpClient = new HttpClient {
                Timeout = timeout == TimeSpan.Zero ? TimeSpan.FromSeconds(30) : timeout
            };
        }

        public Task<HttpResponseMessage> SendAsync(HttpRequestMessage request)
        {
            return httpClient.SendAsync(request);
        }

        public void Dispose()
        {
        }
    }

And then, elsewhere:

    private static readonly ISimpleHttpClient PostmarkClient =
        new PostmarkHttpClient();

    PostmarkClientBase.ClientFactory = () => PostmarkClient;

**Comment by atheken** [comment]
I've just tagged version 4.0.0 with a fix for this issue. It should be available in NuGet within about 10 minutes.

Please let me know if you have any questions.

**Comment by MrKevHunter** [comment]
just had a look, works for me, thanks
