### ISSUE TITLE
Specific version of System.Net.Http really required?

### ISSUE THREAD

**Issue by darrenshrwd** [wildbit/postmark-dotnet#59]
I just updated from 2.2.1 to 3.2.0, it caused me some confusion and issues, your package is now requiring a specific version of System.Net.Http meaning the nuget package for that and a 4x other depended packages are now required.

This has caused a build warning across all the projects in my solution that just use the version that is built into .NET framework ...because they reference the emailing project that uses your newer package.

**Comment by danielcrenna** [comment]
@darrenshrwd It's not required -- it appears vestigial from when the library supported multi-targeting, but since moving to `netstandard2.0` does not need to be there, and indeed interferes with other build systems
