### ISSUE TITLE
PostmarkMessage does not include MetaData property 

### ISSUE THREAD

**Issue by lxalln** [wildbit/postmark-dotnet#60]
Property is defined at http://developer.postmarkapp.com/developer-api-email.html

**Comment by atheken** [comment]
Thanks for the interest @lxalln! Planning to do a release next week that includes this update.

**Comment by lxalln** [comment]
Ok, I guess we will hold off on our integration until next week then.

Thanks for the update, saves me putting the PR in to fix it 👍

**Comment by atheken** [comment]
@lxalln not sure if you're monitoring this the PRs, but we have a patch for this in review, and will probably cut a release to nuget today or tomorrow.

**Comment by lxalln** [comment]
Good news! 👍

**Comment by atheken** [comment]
Version 3.3.0 is released, and includes support for Metadata, as well as other missing APIs. Thanks for your patience while we added them, and please let us know if you have any questions.
