### ISSUE TITLE
Package wont install in C# project

### ISSUE THREAD

**Issue by seattleice** [wildbit/postmark-dotnet#71]
I get this with project set to .Net 4.5, 4.52, 4.6

"Could not install package 'Postmark 4.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files 
that are compatible with that framework. For more information, contact the package author.

**Comment by atheken** [comment]
Hi @seattleice - the current versions of the packages require newer versions of .net, as they are built around .net standard. However, older versions of the postmark can be installed (3.3.0 should be compatible), and it covers the vast majority of our API. If you install those packages and find that there is an API endpoint that you need to access that isn't available, please let us know.

**Comment by seattleice** [comment]
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by seattleice** [comment]
It worked fine in my new test project with the .net version set to 4.6.1



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
