### ISSUE TITLE
Why does PostmarkMessageBase.TrackLinks default to None?

### ISSUE THREAD

**Issue by anton-gogolev** [wildbit/postmark-dotnet#72]
See [PostmarkMessageBase.cs#L19](https://github.com/wildbit/postmark-dotnet/blob/master/src/Postmark/Model/PostmarkMessageBase.cs#L19). On top of that, it's declared as a non-nullable property. This effectively makes it impossible to use Server-level Link Tracking options.

Shouldn't it be declared as `public LinkTrackingOptions? TrackLinks` and set to `null` by default?

(Looks like #70 is already dealing with that).

**Comment by hn3000** [comment]
We just got bit by this problem -- any chance this will be fixed anytime soon?

Thanks!

**Comment by vladsandu** [comment]
Hey @hn3000! I will look into this issue (and the existing PR) and try to have it available during the next couple of days.

**Comment by vladsandu** [comment]
PR Included in version `4.2.1`. Closing this issue.
